apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadspez1929-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadspez1929-tenant-component
    app.kubernetes.io/part-of: loadspez1929-tenant-app
  name: loadspez1929-tenant-component
  namespace: loadspez1929-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadspez1929-tenant-component
    weight: null
status: {}
